version: "3.8"

services:
  device:
    image: foundries/device
    build:
      context: ./
      dockerfile: ./Dockerfile
    user: "${UID_GID-1000:1000}"
    working_dir: /cmddir
    environment:
      FACTORY: $FACTORY
      TOKEN: $TOKEN
      DEVICE_NAME: $DEVICE_NAME
      DEVICE_NAME_PREFIX: $DEVICE_NAME_PREFIX
      HOST_DEVICE_DIR: $DEVICE_DIR
      DEFAULT_APP: $DEFAULT_APP
      DEFAULT_HASH: $DEFAULT_HASH
      DEFAULT_BLOB_HASH: $DEFAULT_BLOB_HASH
      DEVICE_DIR: /device-dir
      DG_IP_ADDR: $DG_IP_ADDR
    volumes:
      - ${CMD_DIR}:/cmddir
      - ${DEVICE_DIR}:/device-dir
    extra_hosts:
      - ostree.foundries.io:34.72.155.201
      - ota-lite.foundries.io:${DG_IP_ADDR-35.226.199.159}
      - api.foundries.io:${API_IP_ADDR-34.66.221.89}
      - hub.foundries.io:${HUB_IP_ADDR-34.121.65.1}

  test-register:
    extends:
      service: device
    environment: 
      DEVICE_DIR: /tmp
      TEST_RUN_NUMB: "1"
    command: bash -c "for ii in {1..$TEST_RUN_NUMB}; do ./register && ./delete-device; done"

  test-registry-pull:
    extends:
      service: test-register
    command: bash -c "for ii in {1..$TEST_RUN_NUMB}; do ./register && ./get-app-blob app-05 ff5538e958fc4dbee49cd037f89f68210900551024fd261a2b677201d08750cc && ./delete-device; done"

  load-hub-creds:
    extends:
      service: test-register
    command:  bash -c "./register && ./go-wrk-basic-auth -c ${GO_WRK_CONCURRENCY} -repeat-numb ${GO_WRK_REQUEST_NUMB} && ./delete-device"

  load-auth-service:
    extends:
      service: test-register
    command:  bash -c "./register && ./go-wrk-token -T 20000 -c ${GO_WRK_CONCURRENCY} -repeat-numb ${GO_WRK_REQUEST_NUMB} && ./delete-device"

  load-registry-proxy:
    extends:
      service: test-register
    command: bash -c "./register && ./go-wrk-app-man -T 20000 -c ${GO_WRK_CONCURRENCY} -repeat-numb ${GO_WRK_REQUEST_NUMB} && ./delete-device"

  load-registry-redirect:
    extends:
      service: test-register
    command: bash -c "./register && ./go-wrk-app-blob -redir -T 40000 -c ${GO_WRK_CONCURRENCY} -repeat-numb ${GO_WRK_REQUEST_NUMB} && ./delete-device"
