#!/bin/bash

app=$1
hash=$2
out_file=${3-/dev/null}

dg_url=$(grep -m1 ^server ${DEVICE_DIR}/sota.toml | cut -d\" -f2)
auth_cred_endpoint="${dg_url}/hub-creds/"
dg_host=$(echo "${dg_url}" | sed -e 's/https:\/\///')

echo ">>> ${dg_url}"
auth_creds=$(curl -s --cacert "${DEVICE_DIR}/root.crt" --cert "${DEVICE_DIR}/client.pem" --key "${DEVICE_DIR}/pkey.pem" "${auth_cred_endpoint}" --resolve "${dg_host}":"${DG_IP_ADDR}")

username=$(echo $auth_creds | jq -r ."Username")
password=$(echo $auth_creds | jq -r ."Secret")
basic_creds="$username:$password"
encoded_basic_creds=$(echo -n "$basic_creds" | base64 -w0)

jwt_token=$(curl -s -H "Authorization: Basic ${encoded_basic_creds}" "https://hub.foundries.io/token-auth/?service=registry&scope=repository:${FACTORY}/${app}:pull" | jq -r .token)

blob_digest=$(curl -s -H "Authorization: Bearer ${jwt_token}" -H "Accept:application/vnd.oci.image.manifest.v1+json" "https://hub.foundries.io/v2/${FACTORY}/${app}/manifests/sha256:${hash}" | jq .layers | jq -r .[0].digest)

status_code=$(curl --write-out %{http_code} -L -s -o "${out_file}" -H "Authorization: Bearer ${jwt_token}"  "https://hub.foundries.io/v2/${FACTORY}/${app}/blobs/${blob_digest}")

if [[ $status_code -eq 200 ]] ; then
        echo "Fetched hub.foundries.io/$FACTORY/$app@$hash archive to $out_file"
        exit 0
else
        echo "Failed to fetch hub.foundries.io/$FACTORY/$app@$hash" 
        exit 1
fi

