#!/bin/bash

export DEVICE_FACTORY=$FACTORY
DEVICE_NAME=${DEVICE-""}
lmp-device-register --start-daemon 0 -n "${DEVICE_NAME}" -T $TOKEN

ostree_server_uri="$(grep -m1 ^ostree_server /var/sota/sota.toml | cut -d\" -f2)"
ostree remote add fio --no-gpg-verify "${ostree_server_uri}" \
  --set=tls-client-cert-path=/var/sota/client.pem \
  --set=tls-client-key-path=/var/sota/pkey.pem \
  --set=tls-ca-path=/var/sota/root.crt

hash="${1-OSTREE_HASH}"
echo "Pulling ${hash} from ${ostree_server_uri}"
ostree pull fio "${hash}" && echo "OK" || echo "Failed"
